name: Manage Dependabot PRs

on:
  pull_request:
    types: [opened, edited]
    branches:
      - '*'

jobs:
  manage-dependabot-prs:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action for Dependabot
        uses: ./.github/actions/manage-pr-issue
        with:
          actor: "dependabot[bot]"
          branches: "main,develop"
          event_types: "pull_request"
          title_prefix: "chore(deps): "
          labels: "dependencies,automated"
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}